"""create core tables

Revision ID: a70e8f6fcbd9
Revises:
Create Date: 2026-07-02 19:58:07.473325

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a70e8f6fcbd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    Monetary columns (app.db.types.Money) are BIGINT integer minor units
    (cents) at the database level — rendered here as sa.BigInteger so this
    migration stays self-contained and portable.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synced", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stores")),
    )
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synced", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_categories_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "sales",
        sa.Column("total_amount", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synced", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_sales_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
    )
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sales_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "products",
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("cost_price", sa.BigInteger(), nullable=False),
        sa.Column("min_sale_price", sa.BigInteger(), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synced", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_products_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_products_barcode"), ["barcode"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "price_tiers",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("min_quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synced", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_price_tiers_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_price_tiers_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_tiers")),
    )
    with op.batch_alter_table("price_tiers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_price_tiers_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_price_tiers_store_id"), ["store_id"], unique=False
        )

    op.create_table(
        "sale_items",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_applied", sa.BigInteger(), nullable=False),
        sa.Column("line_total", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synced", sa.Boolean(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_sale_items_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["sale_id"], ["sales.id"], name=op.f("fk_sale_items_sale_id_sales")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"], ["stores.id"], name=op.f("fk_sale_items_store_id_stores")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_items")),
    )
    with op.batch_alter_table("sale_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sale_items_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sale_items_sale_id"), ["sale_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sale_items_store_id"), ["store_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sale_items_store_id"))
        batch_op.drop_index(batch_op.f("ix_sale_items_sale_id"))
        batch_op.drop_index(batch_op.f("ix_sale_items_product_id"))

    op.drop_table("sale_items")
    with op.batch_alter_table("price_tiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_price_tiers_store_id"))
        batch_op.drop_index(batch_op.f("ix_price_tiers_product_id"))

    op.drop_table("price_tiers")
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_products_store_id"))
        batch_op.drop_index(batch_op.f("ix_products_category_id"))
        batch_op.drop_index(batch_op.f("ix_products_barcode"))

    op.drop_table("products")
    with op.batch_alter_table("sales", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sales_store_id"))

    op.drop_table("sales")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_store_id"))

    op.drop_table("categories")
    op.drop_table("stores")
    # ### end Alembic commands ###
